name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  build-and-publish:
    name: Build and Publish
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=$TAG" >> $GITHUB_OUTPUT
          echo "Version: $TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sab_monitarr:latest
            ghcr.io/${{ github.repository_owner }}/sab_monitarr:${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/sab_monitarr:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/sab_monitarr:buildcache,mode=max
